Rust, React, Raspberry Pi
icgc-dcc/softeng pull request #192
Opened 2020-12-11 02:01 UTC by andricDu

2020-12-11 17:45 UTC, rosibaj requested changes

2020-12-11 17:45 UTC, rosibaj commented on _posts/dusan_andric/2020-12-11-bombolone.md
> +Once I connected it all together, I validate the functionality of the night vision with a simple python script that utilized the picamera API to serve a mjpg stream over HTTP. You can find an example
Once I connected it all together, I `validated` the functionality....

2020-12-11 17:45 UTC, rosibaj commented on _posts/dusan_andric/2020-12-11-bombolone.md
> +Now that I had the hardware assembled, I wanted to see how far I could stretch the python script. I left the script running, accessibly by local network for a time. I quickly ran into stability issue
I left the script running, `accessible` by local network for a time.

2020-12-11 18:20 UTC, rosibaj approved these changes

2020-12-11 18:21 UTC, merged

2021-01-06 15:19 UTC, denis-yuen reviewed
Might be too late since this is merged, but a cool read and will check out buyapi.ca

2021-01-06 15:19 UTC, denis-yuen commented on _posts/dusan_andric/2020-12-11-bombolone.md
> +With the main software components ready, it was time to handle the infrastructure. I needed to figure out how to make my baby monitor reachable form the internet for when I am out the house. I alread
form -> from, out -> out of

2021-01-06 15:19 UTC, denis-yuen commented on _posts/dusan_andric/2020-12-11-bombolone.md
> +I ordered my RPi4 kit from [CanaKit](https://www.canakit.com/) and as time went on I added components that I ordered from [ByAPi.ca](https://www.buyapi.ca/).
BuyAPi -> buyapi.ca