Laravel mobile
icgc-dcc/softeng pull request #54
Opened 2017-03-07 17:43 UTC by baminou

2017-03-09 17:32 UTC, Fgerthoffert commented on _posts/brice_aminou/2017-03-07-Mobile-app-with-Laravel.md
> +Create a new project using composer. If you do not have composer installed, I invite you to look at other solutions to create a new Laravel application [in their
Could you detail what you mean by "look at other solutions". Something like this maybe "We are using composer for X reason, but it has the following limitations .... therefore we recommend looking at other solutions" ?

2017-03-09 17:32 UTC, Fgerthoffert commented on _posts/brice_aminou/2017-03-07-Mobile-app-with-Laravel.md
> +Warning: The permissions of those directories are changed to 777 only for this tutorial. Do not use those permissions in production.
Why, for the purpose of this tutorial are you using 777 ? Maybe add an explanation.

2017-03-09 17:32 UTC, Fgerthoffert commented on _posts/brice_aminou/2017-03-07-Mobile-app-with-Laravel.md
> +This tutorial describes an easy way to create a mobile app from your existing Laravel application. At the end of this tutorial, you will be able to create a hybrid app from an
Maybe add a quick Intro on why using Laravel, versus other tools ? Added benefits or link to a page listing those ?

2017-03-09 18:39 UTC, baminou commented on _posts/brice_aminou/2017-03-07-Mobile-app-with-Laravel.md
> +This tutorial describes an easy way to create a mobile app from your existing Laravel application. At the end of this tutorial, you will be able to create a hybrid app from an
I did not want to talk too much about Laravel, but the post is answering a problem that I had using Laravel and that I was not able to find the explanation online. So I don't want to make any recommendations or comparisons to other tools as there is already a lot of different existing posts comparing the different frameworks.

2017-03-09 19:54 UTC, Fgerthoffert commented
👍

2017-03-09 19:55 UTC, Fgerthoffert approved these changes

2017-03-13 13:49 UTC, andricDu requested changes

2017-03-13 13:49 UTC, andricDu commented on _posts/brice_aminou/2017-03-07-Mobile-app-with-Laravel.md
> +To build a web application, Laravel is comparable to Django (Python) or Ruby on rails (Ruby). The choice of the right Framework to use for your next application if you are not
rails --> Rails

2017-03-13 13:49 UTC, andricDu commented on _posts/brice_aminou/2017-03-07-Mobile-app-with-Laravel.md
> +familiar with any of them would depends on how comfortable you feel with PHP, Python or Ruby. In this post, we are only going to talk about Laravel.
~would~

2017-03-13 13:49 UTC, andricDu commented on _posts/brice_aminou/2017-03-07-Mobile-app-with-Laravel.md
> +At the end of this tutorial, you will be able to create a hybrid app from an existing Laravel project. A hybrid app have many advantages if you are familiar with HTML, CSS and Javascript:
have --> has

2017-03-14 17:11 UTC, Fgerthoffert approved these changes

2017-03-14 17:12 UTC, Fgerthoffert approved these changes

2017-03-15 13:47 UTC, andricDu approved these changes

2017-03-15 13:47 UTC, merged