add bio and avatar for Grant
icgc-dcc/softeng pull request #66
Opened 2017-06-06 14:46 UTC by grant-guo

2017-06-06 14:52 UTC, andricDu requested changes

2017-06-06 14:52 UTC, andricDu commented on _data/authors.yml
> +  info: passionate back-end developer interested in applying distributed data computation software to domains, keep curiosity on new things
Capitalize `Passionate`.

Also for grammatical purposes, you might want to reword:
"... , keep curiosity on new things" to something like "..., forever curious about news things."

2017-06-06 15:21 UTC, KevinFHartmann commented
"..., forever curious about news things."
That should say "forever curious about new things", unless, of course, you're curious about things on the news. [😊]

________________________________
From: Dušan Andrić <notifications@github.com>
Sent: Tuesday, June 6, 2017 10:52:13 AM
To: OICR/softeng-blog
Cc: Subscribed
Subject: Re: [OICR/softeng-blog] add bio and avatar for Grant (#66)


@andricDu requested changes on this pull request.

________________________________

In _data/authors.yml<https://github.com/OICR/softeng-blog/pull/66#discussion_r120383780>:

> @@ -169,4 +169,9 @@ vitalii_slobodianyk:
   avatar: vitalii_slobodianyk.svg
   github: slovit
   is_alumni: true
-
+grant_guo:
+  name: Grant Guo
+  position: Senior Software Developer
+  info: passionate back-end developer interested in applying distributed data computation software to domains, keep curiosity on new things


Capitalize Passionate.

Also for grammatical purposes, you might want to reword:
"... , keep curiosity on new things" to something like "..., forever curious about news things."

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://github.com/OICR/softeng-blog/pull/66#pullrequestreview-42341112>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AZUqQLHd3KucvvV_B5ffLn6K39xoCKRiks5sBWedgaJpZM4Nxc3E>.

2017-06-13 12:52 UTC, grant-guo commented on _data/authors.yml
> +  info: passionate back-end developer interested in applying distributed data computation software to domains, keep curiosity on new things
Thanks

2017-06-13 15:54 UTC, andricDu commented on _data/authors.yml
> +  info: Passionate back-end developer interested in applying distributed data computation software to domains, forever curious about new things
Missing period at the end, and then you will be good to go.

2017-06-13 19:42 UTC, andricDu approved these changes

2017-06-13 19:42 UTC, merged