ID job performance-tuning practice
icgc-dcc/softeng pull request #72
Opened 2017-07-07 17:20 UTC by grant-guo

2017-07-17 16:05 UTC, andricDu requested changes

2017-07-17 16:05 UTC, andricDu commented on _posts/grant_guo/2017-07-07-spark.md
> +In the product environment, DCC-Release ID job takes 20+ hours to finish. The bottleneck is the fact that for every data point ID job needs to talk to DCC-ID service through HTTP request to either ob
`through HTTP request` -> `through a HTTP request`

`even ID service runs multiple instances and the vanish cache runs on a dedicated server with 128G RAM.` -> `even if the ID service runs multiple instances, and the vanish cache runs on a dedicated server with 128G RAM.`

2017-07-17 16:05 UTC, andricDu commented on _posts/grant_guo/2017-07-07-spark.md
> +However I got OutOfMemory exception. I checked the "mutation_ids" table, there are over 80 millions records and each record occupied 1K bytes, which means when loading mutation ID data, approximate 8
`However I got OutOfMemory exception` -> `However I got OutOfMemory exceptions`

2017-07-17 16:05 UTC, andricDu commented on _posts/grant_guo/2017-07-07-spark.md
> +At this point, seems everything is stucked. I decided to think about this in a bottom-up way. The whole process, where ID job talks to ID service to obtain or create an ID for each data point, looks
`At this point, seems everything is stucked.` -> `At this point, it seems like everything is stuck.`

2017-07-17 16:05 UTC, andricDu commented
This is a great post.

2017-07-17 16:07 UTC, andricDu commented
You could use this for your teaser image: https://spark.apache.org/images/spark-logo-trademark.png

![image](https://user-images.githubusercontent.com/6350043/28277616-7d2952e8-6ae8-11e7-8a70-9b7a9920a315.png)

2017-08-09 19:33 UTC, Fgerthoffert approved these changes
Some minor comments, great article.

2017-08-09 19:33 UTC, Fgerthoffert commented on _posts/grant_guo/2017-07-07-spark.md
> +In our product environment, the DCC-Release ID job takes 20+ hours to finish. The bottleneck is the fact that for every data point ID job needs to talk to DCC-ID service through a HTTP request to eit
You should break down this paragraph in shorter sentence, suggested version:

The bottleneck is the fact that, for every data point, the ID job needs to talk to DCC-ID service through a HTTP request to either obtain or create an ID. It means every time the ID job runs there are millions of ID lookup requests. This proves to be challenging, even if ID service runs multiple instances and the vanish cache runs on a dedicated server with 128G RAM.

2017-08-09 19:33 UTC, Fgerthoffert commented on _posts/grant_guo/2017-07-07-spark.md
> +The ID service already has a "****/export" endpoint for each ID type(mutation, sample, donor and specimen) respectively, so the original idea is to cache the exported data at worker nodes locally for
an ... endpoint (instead of a ... endpoint)

2017-08-09 19:33 UTC, Fgerthoffert commented on _posts/grant_guo/2017-07-07-spark.md
> +The first trial is to use Spark Broadcast(https://spark.apache.org/docs/latest/programming-guide.html#broadcast-variables), which is used to give every node a copy of a large input dataset in an effi
replace "which is used to give every node"  by "which gives every node", this also prevent the duplication of "use" in the sentence.

2017-08-09 19:33 UTC, Fgerthoffert commented on _posts/grant_guo/2017-07-07-spark.md
> +However I got OutOfMemory exceptions. I checked the "mutation_ids" table, there are over 80 millions records and each record occupied 1K bytes, which means when loading mutation ID data, approximate
why *the* timeout happened

2017-08-09 19:33 UTC, Fgerthoffert commented on _posts/grant_guo/2017-07-07-spark.md
> +So far Spark broadcast works well for Donor, Sample and Specimen, but failed on Mutation. So the focus is moved to how to load the large dataset of Mutation.
Add comma after "So far"

2017-08-09 19:33 UTC, Fgerthoffert commented on _posts/grant_guo/2017-07-07-spark.md
> +Task scheduling in ID job also could be optimized. So far in the production environment, we have over 70 projects(data sources), 4 types of task(for Donor, Sample, Specimen and Mutation respectively)
Task scheduling in __the__ ID job

2017-08-14 14:17 UTC, merged